version: "3.8"
services:
  web:
    container_name: be-golang
    build: .
    ports:
      - 8090:8888
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 8091:5432
    environment:
      - POSTGRES_DB=go-coffee-shop
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres