services:
  web:
    container_name: be-golang
    build: .
    ports:
      - 8090:8888
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      tesnet:
        ipv4_address: 192.168.10.50
networks:
  tesnet:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1
  db:
    image: postgres
    ports:
      - 8092:5432
    volumes:
      - ./db-data:/var/lib/postgresql/16/main
    environment:
      - POSTGRES_DB=go-coffee-shop
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres